name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
      
      - name: Build linux/amd64
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          go build \
            -ldflags "-X github.com/fivethirty/satisficer/internal/commands.version=${GITHUB_REF_NAME}" \
            -o satisficer main.go
          tar -czf satisficer-linux-amd64.tar.gz satisficer
      
      - name: Generate checksums
        run: |
          sha256sum *.tar.gz > checksums.txt
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            satisficer-linux-amd64.tar.gz
            checksums.txt
          generate_release_notes: true